# Generated by Django 2.2 on 2020-10-08 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration_server',
            name='deployed',
        ),
        migrations.AddField(
            model_name='integration_server',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='integration_server',
            name='has_new_version',
            field=models.IntegerField(verbose_name='Updates Behind'),
        ),
    ]
