# Generated by Django 2.2 on 2020-10-11 13:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_auto_20201008_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIntegrationStatus',
            fields=[
                ('code', models.IntegerField(db_column='Code', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'C_Integration_Status',
                'ordering': ['code'],
            },
        ),
        migrations.RunSQL("""
            INSERT INTO C_Integration_Status (`Code`,`Description`) VALUES (0,'Queued') ;
            INSERT INTO C_Integration_Status (`Code`,`Description`) VALUES (1,'Running') ;
            INSERT INTO C_Integration_Status (`Code`,`Description`) VALUES (2,'Success') ;
            INSERT INTO C_Integration_Status (`Code`,`Description`) VALUES (3,'Failed') ;
        """),
        migrations.RemoveField(
            model_name='integration_server',
            name='done',
        ),
        migrations.AddField(
            model_name='integration_server',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='integration.CIntegrationStatus'),
        ),
    ]
