# Generated by Django 2.2.16 on 2020-10-15 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_Integration_server_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration_server',
            name='author_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='integration_server',
            name='author_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
