# Generated by Django 2.2.16 on 2020-10-16 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_auto_20201015_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration_server',
            name='branch',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
