# Generated by Django 2.2.16 on 2020-10-19 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0006_auto_20201016_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration_server',
            name='coverage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
