# Generated by Django 2.2 on 2020-10-28 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0007_auto_20201019_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciproject',
            name='slackchannel',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
