# Generated by Django 2.2.16 on 2020-11-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0008_auto_20201028_1616'),
    ]

    operations = [
        migrations.RunSQL("""
        UPDATE autodeploy.C_Integration_Status SET `Description` = 'Fail' where `Code` = '3';
        """)
    ]
